# Run command:
# snakemake --reason --cores 44 --cluster "qsub -pe smp 22 -N fig3.3.smk -b y -j y -V -P TumourProgression" -j 2

# DAG command:
# snakemake --dag | dot -Tsvg > dag.svg

# run infercnv with no coverage-based filtering, inflection point and literature-based filtering

# define directories:
R_dir = "/share/ClusterShare/software/contrib/briglo/octR/src/R-3.6.0/builddir/bin/"

#SAMPLES = list(["CID3586", "CID3963", "CID4465", 
#    "CID4523", "CID3921", "CID4066", 
#    "CID44041", "CID4513", "CID4530N",
#    "CID4290A", "CID44991", "CID3941", 
#    "CID4067", "CID4461", "CID4495", 
#    "CID4515", "CID4535", "CID3948",  
#    "CID4463", "CID45171"
#])

SAMPLES = list(["CID4463"])

## random tree samples which work with random tree with 22 cores, p<0.1:
#"CID4066", "CID4515", "CID3921", 
#"CID4067", "CID45171", "CID3941", 
#"CID4523", "CID3948", "CID4463", 
#"CID4530N", "CID3963", "CID44041", 
#"CID4465", "CID4535"])

# samples which did not work with random tree with less than 80 cores, p<0.1:
#"CID4290A", "CID4471", "CID3586", 
#"CID44971", "CID44991", "CID4495",
#"CID4513"

## samples which worked with 20 cores at p<0.05:
#"CID3586", "CID3963", "CID4465", 
#"CID4523", "CID3921", "CID4066", 
#"CID44041", "CID4513", "CID4530N",
#"CID4290A", "CID44991", "CID3941", 
#"CID4067", "CID4461", "CID4495", 
#"CID4515", "CID4535", "CID3948",  
#"CID4463", "CID45171"

## samples which did not work with 20 cores at p<0.05:
#"CID4471", "CID44971", "CID4398"

# infercnv parameters:
file_name="03_seurat_object_processed.Rdata"
SUBCLUSTER_METHOD = list(["random_trees"])
SUBCLUSTER_P = list(["0.1"])
#SUBCLUSTER_METHOD = list(["random_trees"])
#SUBCLUSTER_P = list(["0.05", "0.1"])
res = "PC_A_res.1"
#res = "none"
coverage_filter = "filtered"
nUMI_threshold = "3200"
nGene_threshold = "700"
garnett_slot = "garnett_call_ext_major"
manual_epithelial = "none"
exclude_clusters = "none"

## plot parameters:
remove_artefacts="artefacts_removed"
x_thresh_multiplier="1.5"
y_thresh_multiplier="1.5"
remove_normals="FALSE"
order_by="CNV"
subcluster_annot="TRUE"
subcluster_legend="TRUE"
normal_in_subcluster_annot="TRUE"
normal_annot="FALSE"
normal_legend="FALSE"
plot_references="FALSE"

######
#rule all:
#    input:
#        expand(
#            "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
#            "{subcluster_p}/infercnv.12_denoised.png",
#            sample=SAMPLES, coverage_filter = coverage_filter,
#            subcluster_method=SUBCLUSTER_METHOD, subcluster_p=SUBCLUSTER_P
#        )
######

#######
#rule all:
#    input:
#        expand(
#            "results/infercnv/{sample}/p_0.05/clustered_by_random_trees/plots/infercnv_plot_with_expression_clusters.png",
#            sample=SAMPLES
#        )
#        ,
#        expand(
#            "results/infercnv/{sample}/p_0.05/clustered_by_random_trees/Rdata/3b.filtered_metadata_good_coverage_only.Rdata",
#            sample=SAMPLES
#        )
#####

######
rule all:
    input:
        expand(
            "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/artefacts_removed/plots/" + 
            "infercnv_plot_exp_clusters_CNV_subclusters_QC_annotated.png",
            sample=SAMPLES, coverage_filter=coverage_filter, subcluster_method=SUBCLUSTER_METHOD,
            subcluster_p=SUBCLUSTER_P
        )
#####

rule infercnv:
    input:
        "raw_files/seurat_objects/{sample}/" + file_name,
    output:
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/infercnv.12_denoised.png"
    threads: 22
    shell:
        "module load briglo/R/3.6.0; " + 
        "mkdir -p logs/infercnv/{wildcards.sample}/{wildcards.coverage_filter}/" + 
            "{wildcards.subcluster_method}/p_{wildcards.subcluster_p}/; " +
        "cd logs/infercnv/{wildcards.sample}/{wildcards.coverage_filter}/" + 
            "{wildcards.subcluster_method}/p_{wildcards.subcluster_p}/; " + 
        "{R_dir}/R CMD BATCH  --no-save '--args" + 
        " {wildcards.sample}" + 
        " {file_name}" +
        " {threads}" + 
        " {wildcards.subcluster_method} " + 
        " {wildcards.subcluster_p} " + 
        " {res} " + 
        " {coverage_filter} " + 
        " {nUMI_threshold} " + 
        " {nGene_threshold} " + 
        " {garnett_slot} " + 
        " {manual_epithelial} " + 
        " {exclude_clusters} " + 
        "' ../../../../../../scripts/1.infercnv.R"

rule plot_all_annotations:
    input:
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/infercnv.12_denoised.png"
    output:
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/artefacts_removed/plots/" + 
            "infercnv_plot_exp_clusters_CNV_subclusters_QC_annotated.png"
    threads: 2
    shell:
        "module load briglo/R/3.6.0; "
        "mkdir -p logs/plot/{wildcards.sample}/; " +
        "cd logs/plot/{wildcards.sample}; " + 
        "{R_dir}/R CMD BATCH  --no-save '--args" + 
        " {wildcards.sample}" + 
        " {wildcards.subcluster_method}" +
        " {wildcards.subcluster_p}" +
        " {wildcards.coverage_filter}" +
        " {remove_artefacts}" +
        " {x_thresh_multiplier}" +
        " {y_thresh_multiplier}" +
        " {remove_normals}" +
        " {order_by}" +
        " {subcluster_annot}" +
        " {subcluster_legend}" +
        " {normal_in_subcluster_annot}" +
        " TRUE" +  # expression_annot
        " TRUE" + # expression_legend
        " TRUE" + # QC_annot
        " {normal_annot}" +
        " {normal_legend}" +
        " {plot_references}" +
        "' ../../../scripts/2.plot_individual_heatmap.R"

#rule plot_CNV_only:
#    input:
#        "results/infercnv/{sample}/p_0.05/infercnv.12_denoised.png"
#    output:
#        infercnv = "results/infercnv/{sample}/p_0.05/clustered_by_random_trees/plots/infercnv_plot_with_expression_clusters.png"
#        #,metadata = "results/infercnv/{sample}/p_0.05/clustered_by_random_trees/Rdata/3b.filtered_metadata_good_coverage_only.Rdata"
#    threads: 2
#    shell:
#        "module load briglo/R/3.6.0; "
#        "mkdir -p logs/plot/{wildcards.sample}/; " +
#        "cd logs/plot/{wildcards.sample}; " + 
#        "{R_dir}/R CMD BATCH  --no-save '--args" + 
#        " {wildcards.sample}" +  
#        " {all_cell_PC}" + 
#        " {all_cell_res}" + 
#        " {malignant_PC}" +
#        " {malignant_res}" +
#        " {broad_markers}" +
#        " {epithelial_markers}" +
#        " {nUMI_threshold}" +
#        " {nGene_threshold}" +
#        " {min_proportion_cells_for_subcluster}" +
#        " 0.05" +
#        " random_trees" +
#        "' ../../../scripts/2.plot_individual_heatmap.R"



