# Run command:
# snakemake --reason --cores 60 --cluster "qsub -pe smp 3 -N fig2.2.smk -b y -j y -V -P TumourProgression" -j 20

# DAG command:
# snakemake --dag | dot -Tsvg > dag.svg

# run infercnv with no coverage-based filtering, inflection point and literature-based filtering

# define directories:
R_dir = "/share/ClusterShare/software/contrib/briglo/octR/src/R-3.6.0/builddir/bin/"

## following samples need 20 cores:
#SAMPLES = list([
#  "CID3941", "CID4067", "CID4290A", 
#  "CID4463", "CID4530N", "CID4535",
#  "CID3921", "CID3586", "CID3963", "CID4066", "CID45171",
#  "CID44971", "CID44991", "CID4513",
#  "CID4515", "CID4523"
#])
#SAMPLES = list(["CID45152", "CID45172"])
SAMPLES = list([
  "CID4066", "CID44971",
  "CID45152", "CID45172",
  
])


# infercnv parameters:
file_name="03_seurat_object_processed.Rdata"
res = "PC_A_res.1"
coverage_filter = "filtered"
nUMI_threshold = "3200"
nGene_threshold = "700"
garnett_slot = "garnett_call_ext_major"
manual_epithelial = "none"
exclude_clusters = "none"

# plot parameters:
remove_artefacts="artefacts_not_removed"
epi_res="PC_C_res.1"
epi_PC="C"
x_outlier_multiplier="1.5"
x_thresh_multiplier="3"
y_outlier_multiplier="1.5"
y_thresh_multiplier="3"
subcluster_method="random_trees"
subcluster_p="0.05"
min_cluster_cells="5"
subcluster_merge="TRUE"
merge_thresh="0.95"
merge_diff_prop="0.75"
plot_references="FALSE"
array_CNVs = "FALSE"

# expression plot parameters:
met="FALSE"
res="PC_C_res.1"
PC="C"
remove_outliers="TRUE"
outlier_sd_multiplier=3
normal_markers="EPCAM_KRT18_ESR1_KRT5_KRT14_PGR_ERBB2_MKI67"
epi_markers="EPCAM_KRT18_ESR1_KRT5_KRT14_PGR_ERBB2_MKI67"
custom_epi_markers="ELF5_GATA3_CD44_ZEB1_MUCL1_NDRG1_IGFBP5"

# signal plot parameters:
min_CNV_length = "20"
min_CNV_proportion = "0.5"

# DE parameters:
adj_p_cutoff = "0.1"
specific_DE = "none"
specific_features = "none"

# collated heatmap parameters:
gene_proportion_threshold = "0.5"

######
#rule all:
#    input:
#        expand(
#            "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
#            "{subcluster_p}/infercnv.12_denoised.png",
#            sample=SAMPLES, coverage_filter = coverage_filter,
#            subcluster_method=subcluster_method, subcluster_p=subcluster_p
#        )
#######

######
rule all:
    input:
        expand(
            "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/plots/" + 
            "infercnv_plot_normals_QC_annotated.pdf",
            sample=SAMPLES, coverage_filter=coverage_filter, 
            subcluster_method=subcluster_method, subcluster_p=subcluster_p,
            remove_artefacts=remove_artefacts
        )
#        ,
#        expand(
#            "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
#            "{subcluster_p}/{remove_artefacts}/plots/expression_plots/" + 
#            "all_cells_UMAP.png",
#            sample=SAMPLES, coverage_filter=coverage_filter, 
#            subcluster_method=subcluster_method, subcluster_p=subcluster_p,
#            remove_artefacts=remove_artefacts
#        )
#        ,
#        expand(
#            "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
#            "{subcluster_p}/{remove_artefacts}/plots/DE/" + 
#            "top_subpop_DE_CNA_assoc.png",
#            sample=SAMPLES, coverage_filter=coverage_filter, 
#            subcluster_method=subcluster_method, subcluster_p=subcluster_p,
#            remove_artefacts=remove_artefacts
#        ),
#        expand(
#            "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
#            "{subcluster_p}/{remove_artefacts}/tables/" + 
#            "all_subpop_DE.txt",
#            sample=SAMPLES, coverage_filter=coverage_filter, 
#            subcluster_method=subcluster_method, subcluster_p=subcluster_p,
#            remove_artefacts=remove_artefacts
#        ),
#        expand(
#            "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
#            "{subcluster_p}/{remove_artefacts}/tables/" + 
#            "top_subpop_DE_CNA_assoc.txt",
#            sample=SAMPLES, coverage_filter=coverage_filter, 
#            subcluster_method=subcluster_method, subcluster_p=subcluster_p,
#            remove_artefacts=remove_artefacts
#        )
#        ,
#        expand(
#            "results/infercnv/combined_infercnv/{coverage_filter}/{subcluster_method}/p_" + 
#            "{subcluster_p}/{remove_artefacts}/plots/" + 
#            "combined_infercnv_heatmap_rescaled.pdf",
#            coverage_filter=coverage_filter, subcluster_method=subcluster_method, 
#            subcluster_p=subcluster_p, remove_artefacts=remove_artefacts
#        )

rule infercnv:
    input:
        "raw_files/seurat_objects/{sample}/" + file_name,
    output:
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/infercnv.12_denoised.png",
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/Rdata/initial_metadata.Rdata"
    threads: 20
    shell:
        "module load briglo/R/3.6.0; " + 
        "mkdir -p logs/infercnv/{wildcards.sample}/{wildcards.coverage_filter}/" + 
            "{wildcards.subcluster_method}/p_{wildcards.subcluster_p}/; " +
        "cd logs/infercnv/{wildcards.sample}/{wildcards.coverage_filter}/" + 
            "{wildcards.subcluster_method}/p_{wildcards.subcluster_p}/; " + 
        "{R_dir}/R CMD BATCH  --no-save '--args" + 
        " {wildcards.sample}" + 
        " {file_name}" +
        " {threads}" + 
        " {wildcards.subcluster_method}" + 
        " {wildcards.subcluster_p}" + 
        " {res}" + 
        " {coverage_filter}" + 
        " {nUMI_threshold}" + 
        " {nGene_threshold}" + 
        " {garnett_slot}" + 
        " {manual_epithelial}" + 
        " {exclude_clusters}" + 
        "' ../../../../../../scripts/1.infercnv.R"

rule plot_normal_annotations:
    input:
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/infercnv.12_denoised.png",
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/Rdata/initial_metadata.Rdata"
    output:
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/plots/" + 
            "infercnv_plot_normals_QC_annotated.pdf"
    threads: 3
    shell:
        "module load briglo/R/3.6.0; "
        "mkdir -p logs/plot_normal_annot/{wildcards.sample}/; " +
        "cd logs/plot_normal_annot/{wildcards.sample}; " + 
        "{R_dir}/R CMD BATCH  --no-save '--args" + 
        " {wildcards.sample}" + 
        " {wildcards.subcluster_method}" +
        " {wildcards.subcluster_p}" +
        " {wildcards.coverage_filter}" +
        " {remove_artefacts}" +
        " {epi_res}" +
        " {epi_PC}" +
        " {x_outlier_multiplier}" +
        " {x_thresh_multiplier}" +
        " {y_outlier_multiplier}" +
        " {y_thresh_multiplier}" +
        " {min_cluster_cells}" + 
        " {subcluster_merge}" +
        " {merge_thresh}" +
        " {merge_diff_prop}" +
        " CNV" + # order by
        " TRUE" + # QC_annot
        " {plot_references}" +
        " FALSE" + # array CNVs
        " normals_annotated" +
        "' ../../../scripts/2.plot_individual_heatmap.R"

rule plot_subcluster_annotations:
    input:
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/infercnv.12_denoised.png"
    output:
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/plots/" + 
            "infercnv_plot_exp_clusters_CNV_subclusters_QC_annotated.pdf"
    threads: 3
    shell:
        "module load briglo/R/3.6.0; "
        "mkdir -p logs/plot_subcluster_annot/{wildcards.sample}/; " +
        "cd logs/plot_subcluster_annot/{wildcards.sample}; " + 
        "{R_dir}/R CMD BATCH  --no-save '--args" + 
        " {wildcards.sample}" + 
        " {wildcards.subcluster_method}" +
        " {wildcards.subcluster_p}" +
        " {wildcards.coverage_filter}" +
        " {remove_artefacts}" +
        " {epi_res}" +
        " {epi_PC}" +
        " {x_outlier_multiplier}" +
        " {x_thresh_multiplier}" +
        " {y_outlier_multiplier}" +
        " {y_thresh_multiplier}" +
        " {min_cluster_cells}" + 
        " {subcluster_merge}" +
        " {merge_thresh}" +
        " {merge_diff_prop}" +
        " CNV" + # order by
        " TRUE" + # QC_annot
        " {plot_references}" +
        " FALSE" + # array CNVs
        " clusters_annotated" +
        "' ../../../scripts/2.plot_individual_heatmap.R"

rule expression_plots:
    input:
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/plots/" + 
            "infercnv_plot_normals_QC_annotated.pdf"
    output:
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/plots/expression_plots/" + 
            "all_cells_UMAP.png"
    threads: 3
    shell:
        "module load briglo/R/3.6.0; "
        "mkdir -p logs/expression_plots/{wildcards.sample}/; " +
        "cd logs/expression_plots/{wildcards.sample}; " + 
        "{R_dir}/R CMD BATCH  --no-save '--args" + 
        " {wildcards.sample}" + 
        " {wildcards.subcluster_method}" +
        " {wildcards.subcluster_p}" +
        " {wildcards.coverage_filter}" +
        " {remove_artefacts}" +
        " {met}" + 
        " {res}" + 
        " {PC}" +
        " {epi_res}" +
        " {epi_PC}" +
        " {garnett_slot}" +
        " {remove_outliers}" +
        " {outlier_sd_multiplier}" +
        " {normal_markers}" +
        " {epi_markers}" +
        " {custom_epi_markers}" +
        "' ../../../scripts/3.plot_umaps.R"

rule signal_plots:
    input:
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/plots/" + 
            "infercnv_plot_exp_clusters_CNV_subclusters_QC_annotated.pdf"
    output:
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/Rdata/" + 
            "CNV_indices_and_lengths.Rdata"
    threads: 3
    shell:
        "module load briglo/R/3.6.0; "
        "mkdir -p logs/signal_plots/{wildcards.sample}/; " +
        "cd logs/signal_plots/{wildcards.sample}; " + 
        "{R_dir}/R CMD BATCH  --no-save '--args" + 
        " {wildcards.sample}" + 
        " {wildcards.subcluster_method}" +
        " {wildcards.subcluster_p}" +
        " {wildcards.coverage_filter}" +
        " {remove_artefacts}" +
        " {min_CNV_length}" + 
        " {min_CNV_proportion}" +
        " TRUE" + # normals removed?
        "' ../../../scripts/4.signal_plots.R"

rule subcluster_DE:
    input:
         "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/Rdata/" + 
            "CNV_indices_and_lengths.Rdata"
    output:
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/plots/DE/" + 
            "top_subpop_DE_CNA_assoc.png",
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/tables/" + 
            "all_subpop_DE.txt",
        "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/tables/" + 
            "top_subpop_DE_CNA_assoc.txt"
    threads: 3
    shell:
        "module load briglo/R/3.6.0; "
        "mkdir -p logs/DE/{wildcards.sample}/; " +
        "cd logs/DE/{wildcards.sample}; " + 
        "{R_dir}/R CMD BATCH  --no-save '--args" + 
        " {wildcards.sample}" + 
        " {wildcards.subcluster_method}" +
        " {wildcards.subcluster_p}" +
        " {wildcards.coverage_filter}" +
        " {remove_artefacts}" + 
        " {adj_p_cutoff}" +
        " {specific_DE}" +
        " {specific_features} " +
        "' ../../../scripts/6.subcluster_DE.R"

rule collated_heatmap:
    input:
        expand(
            "results/infercnv/{sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/plots/" + 
            "infercnv_plot_exp_clusters_CNV_subclusters_QC_annotated.pdf",
            sample=SAMPLES, coverage_filter=coverage_filter, 
            subcluster_method=subcluster_method, subcluster_p=subcluster_p,
            remove_artefacts=remove_artefacts
        )
    output:
        "results/infercnv/combined_infercnv/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/plots/combined_infercnv_heatmap_rescaled.pdf"
    threads: 3
    shell:
        "module load briglo/R/3.6.0; "
        "mkdir -p logs/combined_infercnv/; " +
        "cd logs/combined_infercnv/; " + 
        "{R_dir}/R CMD BATCH  --no-save '--args" +
        " {wildcards.subcluster_method}" +
        " {wildcards.subcluster_p}" +
        " {wildcards.coverage_filter}" +
        " {remove_artefacts}" +
        " FALSE" + # subset data
        " FALSE" + # subset samples
        " white" + # NA colour
        " {gene_proportion_threshold}" +
        " TRUE" + # QC annot
        " TRUE" + # include metabric
        "' ../../scripts/6.plot_collated_heatmap.R"
    
rule collated_metadata:
    input:
        expand(
            "results/infercnv/combined_CNV_stats/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/plots/" + 
            "CNV_signal_plots.pdf",
            sample=SAMPLES, coverage_filter=coverage_filter, 
            subcluster_method=subcluster_method, subcluster_p=subcluster_p,
            remove_artefacts=remove_artefacts
        )
    output:
        "results/infercnv/combined_CNV_stats/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/plots/subcluster_numbers.pdf"
    threads: 3
    shell:
        "module load briglo/R/3.6.0; "
        "mkdir -p logs/combined_CNV_stats/; " +
        "cd logs/combined_CNV_stats; " + 
        "{R_dir}/R CMD BATCH  --no-save '--args" + 
         " {wildcards.subcluster_method}" +
         " {wildcards.subcluster_p}" +
         " {wildcards.coverage_filter}" +
         " {remove_artefacts}" + 
         " FALSE" + # subset samples
        "' ../../scripts/7.plot_collated_metadata.R"
    
rule plot_matched_mets:
    input:
         "results/infercnv/{met_sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/plots/" + 
            "infercnv_plot_exp_clusters_CNV_subclusters_QC_annotated.pdf"
    output:
        "results/infercnv/{met_sample}/{coverage_filter}/{subcluster_method}/p_" + 
            "{subcluster_p}/{remove_artefacts}/plots/DE/" +
            "CNA_met_assoc_DE_genes.txt"
    threads: 3
    shell:
        "module load briglo/R/3.6.0; "
        "mkdir -p logs/matched_met/{wildcards.met_sample}/; " +
        "cd logs/matched_met/{wildcards.met_sample}; " + 
        "{R_dir}/R CMD BATCH  --no-save '--args" + 
        " {patient_names}"
        " {wildcards.subcluster_method}" +
        " {wildcards.subcluster_p}" +
        " {wildcards.coverage_filter}" +
        " {remove_artefacts}" + 
        " FALSE" + # subset samples
        "' ../../../scripts/8.plot_matched_met_heatmaps.R"




