samples:
  #CID4408: raw_files/seurat_object/CID4408/03_seurat_object_processed.Rdata
  #PDX4408: raw_files/seurat_object/PDX4408/03_seurat_object_processed.Rdata
  CID4386: raw_files/seurat_object/CID4386/03_seurat_object_processed.Rdata
  CID43862: raw_files/seurat_object/CID43862/03_seurat_object_processed.Rdata
  CID43863: raw_files/seurat_object/CID43863/03_seurat_object_processed.Rdata
  #PDX4386: raw_files/seurat_object/PDX4386/03_seurat_object_processed.Rdata
  #PDX43862: raw_files/seurat_object/PDX43862/03_seurat_object_processed.Rdata
  #CID44971: raw_files/seurat_object/CID44971/03_seurat_object_processed.Rdata
  CID44972: raw_files/seurat_object/CID44972/03_seurat_object_processed.Rdata
  #CID44991: raw_files/seurat_object/CID44991/03_seurat_object_processed.Rdata
  CID44992: raw_files/seurat_object/CID44992/03_seurat_object_processed.Rdata
  #CID45171: raw_files/seurat_object/CID45171/03_seurat_object_processed.Rdata
  CID45172: raw_files/seurat_object/CID45172/03_seurat_object_processed.Rdata
  CID4530: raw_files/seurat_object/CID4530/03_seurat_object_processed.Rdata
  #CID4530N: raw_files/seurat_object/CID4530N/03_seurat_object_processed.Rdata
subset_data: FALSE
include_t_cells: TRUE
cancer_x_threshold_sd_multiplier: 2
cancer_y_threshold_sd_multiplier: 1.5
normal_x_threshold_sd_multiplier: 1
normal_y_threshold_sd_multiplier: 1.25
analysis_mode: samples