# snakemake --reason --cluster "qsub -pe smp 20 -N smk.infercnv -b y -j y -V -P TumourProgression" -j 10

configfile: "config.yaml"

# directories:
R_dir = "/share/ClusterShare/software/contrib/CTP_single_cell/tools/R_developers/config_R-3.5.0/bin"

rule all:
    input:
        expand(
            "results/infercnv/t_cells_included/{sample}/" +
            "plots/infercnv_plot.png",
            sample=config["samples"]
        )

rule infercnv:
    input:
        "raw_files/seurat_objects/{sample}/" +
            "03_seurat_object_processed.Rdata"
    output:
        final_observations = protected(
            "results/infercnv/t_cells_included/{sample}/" +
            "infercnv.12_denoised.observations.txt"
        )
    params:
        include_t_cells=config["include_t_cells"]

    threads: 20
    shell:
            "mkdir -p logs/{wildcards.sample}/; " +
            "cd logs/{wildcards.sample}/; " +
            R_dir + "/R CMD BATCH  --no-save '--args {wildcards.sample} " +
            "{params.include_t_cells}' ../../scripts/1.infercnv.R"

rule individual_plot:
    input:
        "results/infercnv/t_cells_included/{sample}/" +
        "infercnv.12_denoised.observations.txt"
    output:
        infercnv_plot = "results/infercnv/t_cells_included/{sample}/"
            "plots/infercnv_plot.pdf"
    params:
        include_t_cells=config["include_t_cells"],
        cancer_x_threshold_sd_multiplier=config["cancer_x_threshold_sd_multiplier"],
        cancer_y_threshold_sd_multiplier=config["cancer_y_threshold_sd_multiplier"],
        normal_x_threshold_sd_multiplier=config["normal_x_threshold_sd_multiplier"],
        normal_y_threshold_sd_multiplier=config["normal_y_threshold_sd_multiplier"],
        reclustered_group_annotation=config["reclustered_group_annotation"],
        epithelial_markers=config["epithelial_markers"]
    threads: 10
    shell:
        "cd logs/{wildcards.sample}/; " +
        R_dir + "/R CMD BATCH  --no-save '--args {wildcards.sample} " +
        "{params.include_t_cells}  " +
        "{params.cancer_x_threshold_sd_multiplier} " +
        "{params.cancer_y_threshold_sd_multiplier} " +
        "{params.normal_x_threshold_sd_multiplier} " +
        "{params.normal_y_threshold_sd_multiplier} " +
        "{params.reclustered_group_annotation} " + 
        "{params.epithelial_markers}' ../../scripts/2.plot_individual_heatmap.R"

rule pdf2png:
    input:
        "results/infercnv/t_cells_included/{sample}/plots/infercnv_plot.pdf"
    output:
        "results/infercnv/t_cells_included/{sample}/plots/infercnv_plot.png"
    shell:
        "convert -density 150 {input} -quality 90 {output}"
