# snakemake --reason --cores 120 --cluster "qsub -pe smp 10 -N smk.infercnv -b y -j y -V -P TumourProgression" -j 12

# define directories:
R_dir = "/share/ClusterShare/software/contrib/briglo/octR/src/R-3.6.0/builddir/bin/"

# define variables:
SAMPLES = list(range(1, 31, 1))
#SAMPLES = list([8])
SAMPLES = list(map(str, SAMPLES))
PROPORTIONS = ["0.9", "0.8", "0.7", "0.6", "0.5", "0.4", "0.3", "0.2", "0.15", "0.1", "0.05", "no", \
    "0.9_gene", "0.8_gene", "0.7_gene", "0.6_gene", "0.5_gene", "0.4_gene", "0.3_gene", "0.2_gene", \
    "0.15_gene", "0.1_gene", "0.05_gene"]
#PROPORTIONS = ["0.6"]

# infercnv parameters:
sample_name = "CID4520N_cancer_sim"
ncores = "10"
subset_data="FALSE"
include_t_cells="TRUE"
analysis_mode="samples"
downsample="TRUE"
CNV_type="both"

# individual plot parameters:
min_CNV_proportion="0.5"
nUMI_threshold="25000"
nGene_threshold="5000"

rule all:
    input:
        expand(
            "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
            "both/{sample}/{proportion}_downsampling/samples_mode/plots/" + 
            "infercnv_plot_with_marked_CNVs.png",
            sample=SAMPLES, proportion=PROPORTIONS
        )

######
#rule all:
#    input:
#        expand(
#            "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
#            "both/{sample}/{proportion}_downsampling/samples_mode/infercnv.12_denoised.png",
#            sample=SAMPLES, proportion=PROPORTIONS
#        )
######

rule infercnv:
    input:
        matrix = "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
            "both/{sample}/{proportion}_downsampling/input_files/input_matrix.txt",
        metadata = "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
            "both/{sample}/{proportion}_downsampling/input_files/metadata.txt"
    output:
        "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
            "both/{sample}/{proportion}_downsampling/samples_mode/infercnv.12_denoised.png"
    threads: 10
    shell:
            "module load briglo/R/3.6.0; "
            "mkdir -p logs/{wildcards.sample}/{wildcards.proportion}_downsampling/; " +
            "cd logs/{wildcards.sample}/{wildcards.proportion}_downsampling/; " + 
#            "touch ../../../{output}; " + 
#            "echo '" + R_dir + "/R CMD BATCH  --no-save --args " + sample_name + " " + 
            R_dir + "/R CMD BATCH  --no-save '--args " + sample_name + " " + 
            ncores + " " + subset_data + " " + include_t_cells + " " + analysis_mode + " " + 
            downsample + " {wildcards.proportion} " + CNV_type + " {wildcards.sample}" + 
            " ../../../scripts/2b.simulated_cancer_infercnv.R"
#            "' > ../../../results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
#            "both/{wildcards.sample}/{wildcards.proportion}_downsampling/samples_mode/command_eg.txt"
          

            "' ../../../scripts/2b.simulated_cancer_infercnv.R"

rule individual_plot:
    input:
        infercnv_output = "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
            "both/{sample}/{proportion}_downsampling/samples_mode/infercnv.12_denoised.png",
        nondownsampled_output = "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
            "both/{sample}/no_downsampling/samples_mode/infercnv.12_denoised.png"

    output:
        "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
            "both/{sample}/{proportion}_downsampling/samples_mode/plots/" + 
            "infercnv_plot_with_marked_CNVs.png"
    threads: 6

    shell:
            "cd logs/{wildcards.sample}/{wildcards.proportion}_downsampling/; " +
            R_dir + "/R CMD BATCH  --no-save '--args " + sample_name + " " + include_t_cells + 
            " " + " {wildcards.sample} " + " {wildcards.proportion} " + " " + analysis_mode + " " + 
            min_CNV_proportion + " " + nUMI_threshold + " " + nGene_threshold + " " + 
            CNV_type + "' ../../../scripts/3b.plot_individual_heatmap.R"

