sample_name: "CID4520N"
subset_data: "FALSE"
nUMI_threshold: 25000
nGene_threshold: 5000
CNV_no_range: "10_40"
CNV_lengths: "25_50_75_100_150_200_300_400"
CNV_multipliers: "3_2_1.5_0.5_0"
downsample: "TRUE"
downsample_proportions: "0.9_0.8_0.7_0.6_0.5_0.4_0.3_0.2_0.15_0.1_0.05"
number_simulations: 1:30