# snakemake --reason --cores 120 --cluster "qsub -pe smp 10 -N smk.infercnv -b y -j y -V -P TumourProgression" -j 12

# DAG command:
# snakemake --dag | dot -Tsvg > dag.svg

# define directories:
R_dir = "/share/ClusterShare/software/contrib/briglo/octR/src/R-3.6.0/builddir/bin/"

# define variables:
SAMPLES = list(range(1, 31, 1))
#SAMPLES = list(range(1, 3, 1))
#SAMPLES = list(map(str, SAMPLES))
#SAMPLES = list("2")

PROPORTIONS = ["0.9", "0.8", "0.7", "0.6", "0.5", "0.4", "0.3", "0.2", "0.15", "0.1", "0.05", "no", \
    "0.9_gene", "0.8_gene", "0.7_gene", "0.6_gene", "0.5_gene", "0.4_gene", "0.3_gene", "0.2_gene", \
    "0.15_gene", "0.1_gene", "0.05_gene"]
#PROPORTIONS = ["no", "0.6"]

# simulation parameters:

# infercnv parameters:

# individual plot parameters:

#rule all:
#    input:
#        expand(
#            "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
#            "both/{sample}/{proportion}_downsampling/samples_mode/plots/" + 
#            "infercnv_plot_with_marked_CNVs.png",
#            sample=SAMPLES, proportion=PROPORTIONS
#        )

#####
rule all:
    input:
        expand(
            "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
            "subpops/{sample}/{proportion}_downsampling/samples_mode/" + 
            "infercnv.12_denoised.png",
            sample=SAMPLES, proportion=PROPORTIONS
        )
#####

######
#rule all:
#    input:
#        expand(
#            "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
#            "subpops/{sample}/no_downsampling/input_files/input_matrix.txt",
#            sample=SAMPLES
#        )
######

rule simulate_cancer:
    input:
        "raw_files/seurat_objects/CID4520N/03_seurat_object_processed.Rdata"
    output:
        matrix = expand(
            "results/infercnv/CID4520N_cancer_sim/" + 
            "subpops/{{sample}}/{proportion}_downsampling/input_files/input_matrix.txt",
            proportion=PROPORTIONS
        ),
        metadata = expand(
            "results/infercnv/CID4520N_cancer_sim/" + 
            "subpops/{{sample}}/{proportion}_downsampling/input_files/metadata.txt",
            proportion=PROPORTIONS
        )
    threads: 10
    shell:
            "module load briglo/R/3.6.0; "
            "mkdir -p logs/simulate_cancer/{wildcards.sample}; " +
            "cd logs/simulate_cancer/{wildcards.sample}; " + 
            "{R_dir}/R CMD BATCH  --no-save '--args" + 
            " CID4520N" + 
            " FALSE" +
            " 25000" + 
            " 5000" + 
            " 10_50" + 
            " 20_50_75_100_150_150_200_200_250_250_300_300_350_400_450_500_550_600_650_700_750_800" + 
            " 3_2_1.5_0.5_0" + 
            " TRUE" + 
            " 0.9_0.8_0.7_0.6_0.5_0.4_0.3_0.2_0.15_0.1_0.05" + 
            " {wildcards.sample}" + 
            " 5000" + 
            "' ../../../scripts/1.simulate_cancer.R"

rule infercnv:
    input:
        matrix = "results/infercnv/CID4520N_cancer_sim/" + 
            "subpops/{sample}/{proportion}_downsampling/input_files/input_matrix.txt",
        metadata = "results/infercnv/CID4520N_cancer_sim/" + 
            "subpops/{sample}/{proportion}_downsampling/input_files/metadata.txt"
    output:
        "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
            "subpops/{sample}/{proportion}_downsampling/samples_mode/infercnv.12_denoised.png"
    threads: 10
    shell:
            "module load briglo/R/3.6.0; "
            "mkdir -p logs/infercnv/{wildcards.sample}/{wildcards.proportion}/; " +
            "cd logs/simulate_cancer/{wildcards.sample}/{wildcards.proportion}/; " + 
            "{R_dir}/R CMD BATCH  --no-save '--args" + 
            " CID4520N_cancer_sim" + 
            " {threads}" +
            " {wildcards.sample}" + 
            " subclusters" + 
            " 0.1" + 
            " {wildcards.proportion}" + 
            "' ../../../../scripts/2.infercnv.R"

#rule individual_plot:
#    input:
#        infercnv_output = "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
#            "both/{sample}/{proportion}_downsampling/samples_mode/infercnv.12_denoised.png",
#        nondownsampled_output = "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
#            "both/{sample}/no_downsampling/samples_mode/infercnv.12_denoised.png"
#
#    output:
#        "results/infercnv/t_cells_included/CID4520N_cancer_sim/" + 
#            "both/{sample}/{proportion}_downsampling/samples_mode/plots/" + 
#            "infercnv_plot_with_marked_CNVs.png"
#    threads: 6
#
#    shell:
#            "cd logs/{wildcards.sample}/{wildcards.proportion}_downsampling/; " +
#            R_dir + "/R CMD BATCH  --no-save '--args " + sample_name + " " + include_t_cells + 
#            " " + " {wildcards.sample} " + " {wildcards.proportion} " + " " + analysis_mode + " " + 
#            min_CNV_proportion + " " + nUMI_threshold + " " + nGene_threshold + " " + 
#            CNV_type + "' ../../../scripts/3b.plot_individual_heatmap.R"
#
#